jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Install Maven
      run: choco install maven

    - name: Install dependencies (if necessary)
      run: mvn clean install

    - name: Run Tests
      run: mvn test
