name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'TestBranch'  # Default branch to run the tests on

jobs:
  test:
    runs-on: windows-latest  # Run on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository
      with:
        ref: ${{ github.event.inputs.branch }}  # Use the branch input from the manual trigger

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Specify Java version 17
        distribution: 'temurin'  # Specify the Java distribution (Temurin is the recommended option)

    - name: Set up ChromeDriver and Chrome
      uses: actions/setup-chrome@v2  # Use an action to install Chrome and ChromeDriver on the runner
      with:
        version: 'latest'  # Install the latest version of Chrome and ChromeDriver

    - name: Set ChromeDriver path and Chrome path
      run: |
        # Set environment variables for ChromeDriver and Chrome path
        echo "CHROMEDRIVER_PATH=${{ steps.setup-chrome.outputs.chromedriver-path }}" >> $GITHUB_ENV
        echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

    - name: Run Tests in Headless Mode
      run: |
        # Set up the environment variables for headless Chrome
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV  # Inform tests to run in headless mode

        # Run tests with Maven
        mvn test  # Execute the tests with Maven
