name: Run Tests

on:
  workflow_dispatch:  # This enables manual trigger from the GitHub Actions UI

jobs:
  test:
    runs-on: windows-latest  # Run on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Specify Java version 17
        distribution: 'adoptopenjdk'  # You can also use 'zulu' or 'openjdk' distributions

    - name: Install Maven
      run: |
        choco install maven  # Install Maven using Chocolatey package manager for Windows

    - name: Install dependencies (if necessary)
      run: mvn clean install  # This installs the dependencies for your Maven project (if needed)

    - name: Run Tests
      run: mvn test  # Run the tests with Maven
