name: Run Tests

on:
  workflow_dispatch:  # This enables manual trigger from the GitHub Actions UI

jobs:
  test:
    runs-on: windows-latest  # Run on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.12'  # Specify Java version 17

    - name: Run Tests
      run: mvn test  # Run the tests with Maven
