name: Run Tests

on:
  workflow_dispatch:  # This enables manual trigger from the GitHub Actions UI

jobs:
  test:
    runs-on: windows-latest  # Run on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from the repository

    - name: Install dependencies (if necessary)
      run: mvn clean install  # This installs the dependencies for your Maven project (if needed)

    - name: Run Tests
      run: mvn test  # Run the tests with Maven
